### PR TITLE
WEBP support and fopen optimization

### PR DESCRIPTION
**Pull request by sillydong**
1. Enable WEBP type image
2. Add timeout and refer to fopen to avoid time waste and blocked by Hotlink Protection

### CODE REVIEW

**Comment by tommoor** [comment]
@sillydong thanks for this, unfortunately the diff shows every line as changed so I can't properly review this. Please submit a PR with only the lines of code that are required to change :smile:

**Comment by romaricdrigon** [comment]
@sillydong do you have time to work on that one?
I would badly need this. But no one can edit your PR, wcs I can re-open one from my fork.

**Comment by hansott** [comment]
You can ignore whitespace/line-ending things: https://github.com/tommoor/fastimage/pull/10/files?w=1

**Comment by sillydong** [comment]
Sorry I just noticed this notification, I will reedit my code and send pull request again
SORRY AGAIN.

**Comment by sillydong** [comment]
see #12

**Pull request closed without merging**
